services:
  bot_cruce_ma:
    build: .
    command: ["python3", "bot_cruce_ma.py"]
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
    env_file:
      - .env
    environment:
      - TZ=America/Argentina/Buenos_Aires